name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 11 ]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: Xvfb $DISPLAY &
    - name: Run tests on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        mvn -B test -Dtest=!*Manual*,!*Proxy*,!Edge*
    - name: Run tests on macOS
      if: matrix.os == 'macos-latest'
      run: |
        mvn -B test -Dtest=!*Manual*,!*Proxy*
    - name: Run tests on Windows
      if: matrix.os == 'windows-latest'
      run: |
        mvn -B test -Dtest=!*Manual*,!*Proxy*
      shell: cmd
