name: docker-java

on:
  workflow_dispatch:

jobs:
  docker-java:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Run Selenium tests
      run: |
        mvn -B test -Dtest=Docker*
